### ISSUE TITLE
Update conclusions so it matches objectives of tutorial

### ISSUE THREAD

**Issue by zkamvar** [grunwaldlab/audpc_example#4]
The current conclusions are not in line with the questions asked of the tutorial:

> In general, the AUDPC only changes between the fungicide treatments during the last 10 days of the experiment. The "Cutter" seemed to be most resistant to the disease followed by "2137" and "Jagger". The results suggest that the best yields will be obtained when "Cutter" wheat is used and it is treated with fungicide.

Whereas the questions posed in the tutorial:
- How does the size of the fungicide effect compare to the effect of resistance? 
- Would it be the same as resistance?
- Since the fungicide typically is only active for two weeks after application, after looking at your graph, when do you think the fungicide was applied?

Additionally, it's not exactly correct to imply that Jagger has resistance, as it is noted as the "susceptible" variety:

> The following example, based on field data from Kansas (Sparks and Stack, unpublished), illustrates the difference in disease severity for **a variety susceptible to leaf rust, Jagger**, and the resistant cultivars 2137 and Cutter.

Since we are going to be using this for a room full of plant pathologists, it would be a good idea to have this more accurate or their attention might be drawn towards nitpicking the analysis as opposed to the task at hand (creating the Rmd).

**Comment by zachary-foster** [comment]
I was not following the tutorial on the APS website, just using the dataset, but we can follow it if you want. Although, it seems to me that its best to make the content as simplistic as possible so that its obvious that the exercise is not about plant pathology but R markdown. The APS exercise is about plant pathology; ours is about Rmarkdown. Do you think we should do the exercise as described on the website?

I think of susceptibility and resistance to be on a continuum and not mutually exclusive. It seems like a simplification of reality to call one variety susceptible and the others resistant since they all get the disease, just to different degrees. "most resistant" and "least susceptible" seem the same to me, but I will rephrase it if you think it is an issue.

**Comment by zkamvar** [comment]
> The APS exercise is about plant pathology; ours is about Rmarkdown. Do you think we should do the exercise as described on the website?

I think we should do the exercise as described for the simple fact that this will allow our audience to be more comfortable with the subject matter. 

> I think of susceptibility and resistance to be on a continuum and not mutually exclusive.

I think in this context, it's thought of as a positive control. While you can debate the merits of calling something "susceptible" vs "resistant", this is how it's thought of in plant pathology. 

Ultimately, the idea is to present an exercise that our audience will be able to connect to. This is why I'm suggesting to do it the way the APS tutorial presents it. Students learn better if they can connect with the material. I do think it's an issue if we ignore the questions in the tutorial since they are relevant in the scope of plant pathology, which is where our audience is coming from.

**Comment by zachary-foster** [comment]
Ok, i will change it to more closely follow the exercise.

**Comment by zachary-foster** [comment]
This is done.

**Comment by zkamvar** [comment]
> In general, the AUDPC only changes between the fungicide treatments during the last 20 days of the experiment.

It's a bit more accurate to say that the disease progress curve changes, not the AUDPC

**Comment by zachary-foster** [comment]
Good point, I will change it.

**Comment by zachary-foster** [comment]
I think this is done.
